### ISSUE TITLE
Support `import.meta`

### ISSUE THREAD

**Issue by mysticatea** [eslint/eslint#13133]
> https://github.com/tc39/proposals/commit/0c27379ebb525ffebed75584827ce51687af99f8

`import.meta` meta property has arrived at Stage 4 as ES2020. ESLint should support it.

There is work we should do:

- [x] ESTree update: https://github.com/estree/estree/pull/210
- [x] Acorn update: https://github.com/acornjs/acorn/pull/943
- [x] Espree update https://github.com/eslint/espree/pull/441
- [ ] ESLint update https://github.com/eslint/eslint/pull/13196

**Comment by Lonniebiz** [comment]
I'm so glad this is finally stage 4, because I've been eagerly awaiting eslint support for `import.meta` for [over a year](https://stackoverflow.com/questions/54337576/). I hope it isn't too tough to implement.

Does anyone dare to predict an ETA?
