### ISSUE TITLE
Add support for `#x in obj` private-in syntax

### ISSUE THREAD

**Issue by ota-meshi** [eslint/eslint#14811]
**The version of ESLint you are using.**

7.31.0

**The problem you want to solve.**

Support *Ergonomic brand checks for Private Fields* (`#x in obj` syntax) officially, as it has reached stage-4.
refs:
https://github.com/tc39/proposals/blob/master/finished-proposals.md
https://github.com/tc39/proposal-private-fields-in-in

**Your take on the correct solution to problem.**

- [x] Ecma262 update: tc39/ecma262#2290
- [x] ESTree update:  estree/estree#252
   ~~Maybe we just merge https://github.com/estree/estree/blob/master/stage3/private-fields-in-in.md into es2022.md.~~
- [x] Acorn update: acornjs/acorn#1068
- [x] `eslint-visitor-keys` update:  
   Maybe we have no task on it.
- [ ] `espree` update: https://github.com/eslint/espree/pull/521
- [x] `eslint-scope` update:  
   Maybe we have no task on it.
- [ ] `eslint` update: 

**Are you willing to submit a pull request to implement this change?**

It's difficult for me to change the parser.
I may be able to do other necessary work.

**Comment by nzakas** [comment]
The ESTree syntax is effectively done, just waiting for one last 👍. 

Next we are blocked on Acorn

**Comment by ota-meshi** [comment]
I tried the rules of ESLint using acorn which built the source in github repo. But I couldn't find the rule that needed to be changed.
Do you think there are rules that need to be changed?

**Comment by mdjermanovic** [comment]
With `#x in obj` syntax, `#x` can appear in expressions without preceding `.`, and it generally can be adjacent to other tokens on its left side, so this might be seen as a false negative:

```js
/* eslint space-unary-ops: ["error", { "words": false }] */

class C {
    #x;
    *foo(bar) {
        yield #x in bar;
    }
}
```

These are very edge cases, though.

**Comment by nzakas** [comment]
It looks like we are just on the last step here?

**Comment by mdjermanovic** [comment]
Espree needs to update Acorn version. Acorn hasn't released this change yet (v8.5.0 includes class static blocks, but not this syntax).

**Comment by ljharb** [comment]
That's strange, class static blocks have been stage 4 for a week, but class private fields for months.

**Comment by nzakas** [comment]
Open source doesn’t follow predictable schedules. :)

**Comment by ljharb** [comment]
ha, true enough :-)

**Comment by mkubilayk** [comment]
Acorn 8.6 is just released and includes the necessary change: https://github.com/acornjs/acorn/releases/tag/8.6.0.

**Comment by ota-meshi** [comment]
@mkubilayk Thanks for letting me know!
