### ISSUE TITLE
Implement Language Plugins

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#16999]
This issue describes the implementation plan for eslint/rfcs#99, which will take place in several phases:

## Phase 1: Implement external changes

- [x] https://github.com/estools/esquery/pull/139
- [x] https://github.com/estools/esquery/pull/140
- [x] Update `eslint-scope` `ScopeManager` to expose `isNodejsScope()` as public method

## Phase 2: Implement backward-compatible changes

- [x] Implement `SourceCode#getInlineConfig()`
- [x] Implement `SourceCode#getDisableDirectives()`
- [x] Implement `SourceCode#traverse()`
- [x] Copy `context.getAncestors()` to `SourceCode` https://github.com/eslint/eslint/pull/17059
- [x] Copy `context.getDeclaredVariables()` to `SourceCode` https://github.com/eslint/eslint/pull/17059
- [x] Copy `context.getScope()` to `SourceCode` https://github.com/eslint/eslint/pull/17004
- [x] Copy `context.markVariableAsUsed()` to `SourceCode` https://github.com/eslint/eslint/pull/17086
- [x] Copy `parserServices` to `SourceCode` https://github.com/eslint/eslint/pull/17311
- [x] Create `context.cwd` to replace `context.getCwd()` https://github.com/eslint/eslint/pull/17106
- [x] Create `context.sourceCode` to replace `context.getSourceCode()` https://github.com/eslint/eslint/pull/17107
- [x] Create `context.filename` to replace `context.getFilename()` https://github.com/eslint/eslint/pull/17108
- [x] Create `context.physicalFilename` to replace `context.getPhysicalFilename()` https://github.com/eslint/eslint/pull/17111
- [x] Blog post encouraging people to switch to the new APIs

## Phase 4: Deprecation of old APIs (v8.0.0)

- [x] Update `RuleTester` to warn about `context.getAncestors()`
- [x] Update `RuleTester` to warn about `context.getDeclaredVariables()`
- [x] Update `RuleTester` to warn about `context.getScope()`
- [x] Update `RuleTester` to warn about `context.parserServices`
- [x] Update `RuleTester` to warn about  `context.getCwd()`
- [x] Update `RuleTester` to warn about  `context.getSourceCode()`
- [x] Update `RuleTester` to warn about `context.getFilename()`
- [x] Update `RuleTester` to warn about  `context.getPhysicalFilename()`

## Phase 5: Removal of old APIs (v9.0.0)

- [x] Remove `context.getAncestors()`
- [x] Remove `context.getDeclaredVariables()`
- [x] Remove `context.getScope()`
- [x] Remove `context.markVariableAsUsed()`
- [x] Remove `context.parserServices`

## Phase 6: Create JS language object

- [x] Create JS language object with `parse()` and `createSourceCode()`
- [x] Update flat config to have `language` option (also update default config to use JS language object)
- [x] Update `Linter` to call language object for parsing (fallback to JS language for eslintrc)
- [x] Update `Linter` to use `SourceCode#getInlineConfig()`
- [x] Update `Linter` to use `SourceCode#getDisableDirectives()`
- [x] Update `Linter` to use `SourceCode#traverse()`

## Phase 7: Create `@eslint/json` package

- [x] Publish `@eslint/json` 

## Phase 8: Create `@eslint/markdown` package

- [x] https://github.com/eslint/markdown/issues/260

## Phase 9: Ecosystem Updates

- [x] Document how to create languages
- [x] Update `@types/eslint` with language type definitions
- [x] Publish Code Explorer
- [x] Publish blog post announcing Markdown/JSON and Code Explorer

## Phase 10: Removal of old APIs (v10.0.0)

- [x] Remove  `context.getCwd()`
- [x] Remove `context.getSourceCode()`
- [x] Remove `context.getFilename()`
- [x] Remove `context.getPhysicalFilename()`

https://github.com/eslint/eslint/pull/20086

**Comment by snitin315** [comment]
I can also help with phase 2, I can start with `Copy context.markVariableAsUsed() to SourceCode`. @nzakas Let me know if that's ok.

**Comment by nzakas** [comment]
@snitin315 `markVariableAsUsed()` is a bit complicated, so I'd prefer to keep that one. If you could do the next few items (`cwd`, `sourceCode`, `filename`, and `physicalFilename`) that would be a huge help.

**Comment by amareshsm** [comment]
@nzakas I can also help with some items (any of CWD, sourceCode, filename, and physicalFilename) if possible. Can you pls give some context?

**Comment by nzakas** [comment]
@amareshsm if you'd like to take a look at those four, this is the part of the code involved:
https://github.com/eslint/eslint/blob/9d1b8fc60cc31f12618e58c10a2669506b7ce9bf/lib/linter/linter.js#L979-L1000

Basically, we want to create properties where there are currently methods, and then update all of the rules to use the properties instead of the methods.

**Comment by ollie-iterators** [comment]
With https://github.com/eslint/eslint/pull/17086 merged, Copy context.markVariableAsUsed() to SourceCode should be checked off

**Comment by mdjermanovic** [comment]
I'll work on `parserServices`.

**Comment by ollie-iterators** [comment]
With https://github.com/eslint/eslint/pull/17107 merged, Create context.sourceCode to replace context.getSourceCode() should be checked off

**Comment by nzakas** [comment]
@ollie-iterators it seems like you enjoy tracking our tasks, do you have any interest in becoming more involved with the project?

**Comment by nzakas** [comment]
I'm working on `getInlineConfig` next.

**Comment by ollie-iterators** [comment]
> @ollie-iterators it seems like you enjoy tracking our tasks, do you have any interest in becoming more involved with the project?

I haven't thought about that. I might be interested in that.

**Comment by nzakas** [comment]
@ollie-iterators cool. If you want to discuss, swing by [Discord](https://eslint.org/chat) and we'd be happy to chat.

**Comment by mdjermanovic** [comment]
> * Copy `parserServices` to `SourceCode`

I'm working on this now. 

`parserServices` actually already exists on `SourceCode`, so the task is only to update documentation and tests.

**Comment by sam3k** [comment]
TSC group has confirmed this for `v10`
