### ISSUE TITLE
Change Request: Create supported versions policy

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#18621]
### ESLint version

HEAD

### What problem do you want to solve?

Right now, we don't have a documented supported versions policy, which always leads to confusion when we do a major version release.

Traditionally, we have stopped supporting the previous release as soon as start working on the first prerelease of the next major version. For example, we stop working on v8.x once we know we'd like to do a prerelease of v9.x. That often comes as a surprise to users who (rightly or wrongly) expect that we'll continue working on the previous version even after the next version has been released.

### What do you think is the correct solution?

We need to decide how we want to handle this and then document it. To me, there are four potential designations for any major release line (don't focus too much on the names I came up with, we can always change those later):

* **Current -** the version we are currently working on by fixing bugs and adding new features. Right now, this is v9.x.
* **Transitional** - critical bug fixes, security issues, and compatibility with the upcoming version. This begins when we start working on major version prereleases and ends when the major version is released.
* **Maintenance**  - critical bug fixes and security issues only.
* **End of Life (EOL)** - The ESLint team does not make any further changes.

So releases begin as Current, then move to Transitional once we start working on the prereleases of the next major version. When the next major version is released, it moves to Maintenance and after some period of time, moves to EOL.

Right now, we basically go from Current to EOL directly. For v9.x, we actually did an ad-hoc Transitional release for v8.x in order to have compatibility with flat config features in v9.x. Now that we have tooling set up for this, I think it makes sense.

The questions we need to answer:

1. Does this progression make sense? Are any steps missing?
2. How long do we reasonably want to make the Maintenance phase? This would be new to how we do things.

### Participation

- [X] I am willing to submit a pull request for this change.

### Tasks

- [x] Create version support page (https://eslint.org/version-support)
- [x] Add version support link to homepage
- [x] Add "previous versions" to dropdown on docs site
- [x] Add "previous versions" to dropdown on v8.x docs site
- [x] Add "Version Support" to nav on docs site
- [x] Add "Version Support" to nav on v8.x docs site
- [x] Add EOL banner on v8.x docs site
- [x] Add v8.x EOL banner on homepage
- [x] https://github.com/eslint/eslint/issues/18691
- [x] Mark npm packages prior to v8.x as deprecated

**Comment by mdjermanovic** [comment]
> * **Transitional** - critical bug fixes, security issues, and compatibility with the upcoming version. This begins

The last part of the sentence is missing. This begins when we start doing prereleases for the next major version?

**Comment by mdjermanovic** [comment]
> 1\. Does this progression make sense? Are any steps missing?

Makes sense to me, I'm only not sure if there's a need to differentiate between Transitional and Maintenance steps. Perhaps there's no need to have a date restriction for changes we think are important to backport for compatibility reasons (until EOL, of course). 


> 2\. How long do we reasonably want to make the Maintenance phase?

What do we think about 6 months after the next major version is released? (final vX.0.0, not prerelease).

**Comment by mdjermanovic** [comment]
> Now that we have tooling set up for this

Tooling is not 100% set up. It was updated to support previous major while we're still doing prereleases for the next major, but not after we release the final vX.0.0. I could work on updating the tools (`eslint-release` and `Makefile.js`) to support releasing previous versions at any point.

**Comment by mdjermanovic** [comment]
@eslint/eslint-team thoughts about this?

**Comment by aladdin-add** [comment]
> How long do we reasonably want to make the Maintenance phase? This would be new to how we do things.

👍. It often takes quite a while for the community to support new major, e.g. as of I'm writing, eslint v8.57.0 takes ~33% of the total downloads on npm.

6 months also makes sense to me (we can change it later if necessary :))

**Comment by fasttime** [comment]
For the purpose of documentation, maybe we will need a release schedule or calendar, like [this one](https://nodejs.org/en/about/previous-releases#release-schedule) from Node.js, and possibly a process to update it semi-automatically. For example, when we start working on `v10.0.0-alpha`, we would like to let users know that the _current_ version is now v10.x while the `latest` and `next` links still point to the v9 docs.

**Comment by nzakas** [comment]
> Makes sense to me, I'm only not sure if there's a need to differentiate between Transitional and Maintenance steps. Perhaps there's no need to have a date restriction for changes we think are important to backport for compatibility reasons (until EOL, of course).

@mdjermanovic that's a good observation. Those could very well be merged into just a "Maintenance" status. 

> Tooling is not 100% set up. It was updated to support previous major while we're still doing prereleases for the next major, but not after we release the final vX.0.0. I could work on updating the tools (eslint-release and Makefile.js) to support releasing previous versions at any point.

Ah, I thought it would still work provided that we do something like release v8.x and then immediately release v9.x afterwards. I think it's worth putting in the work necessary to support releases of two different versions.

> For the purpose of documentation, maybe we will need a release schedule or calendar, like [this one](https://nodejs.org/en/about/previous-releases#release-schedule) from Node.js, and possibly a process to update it semi-automatically. For example, when we start working on `v10.0.0-alpha.0`, we will want to let users know that the _current_ version is now v10.x while the `latest` and `next` links still point to the v9 docs.

@fasttime that would be nice! If we could tie it to the release process and automatically update, that would be helpful. Although, we can probably get away with manually updating just once when we start preleases and again once the final major release is published.

**Comment by fasttime** [comment]
I'm fine with having just a _Maintenance_ status and no _Transitional_.

If we want a release schedule diagram we could start by annotating the necessary information for the v8 and v9 releases. Maybe it will be sufficient to update the data whenever we decide to start working on a new major release, or when we are ready to release the first version of a major release (this affects the duration of the maintenance phase of the previous release). The diagram itself could be generated using Mermaid or a similar tool, or directly as a vector graphics file when the website is deployed. For example:

```mermaid
gantt
    title ESLint Release Schedule
    dateFormat  YYYY-MM-DD
    section ESLint v8
    Current                 :v8-1, 2023-11-01, 2023-12-16
    Maintenance             :v8-2, after v8-1, 2024-10-05
    End of Life             :v8-3, after v8-2, 2024-10-31
    section ESLint v9
    ESLint v9.0.0 released  :milestone, v9-0, 2024-04-05,
    Current                 :active, v9-1, 2023-12-16, 2024-08-01
    TBD                     :v9-x, after v9-1, 2024-10-31
```

When we define a “version support policy” statement as per https://github.com/eslint/eslint.org/issues/594, we will double-check that the release schedule aligns to that policy.

**Comment by nzakas** [comment]
Ooh very nice!

I think the next question is where should this policy live? If we put it in the docs, then we'll have multiple copies, one for each version, which doesn't seem correct.

Maybe it should live at eslint.org/version-support so there's just one source of truth to link to?

**Comment by nzakas** [comment]
I put together a version support page here:
https://github.com/eslint/eslint.org/pull/600

Tried to include the relevant information, but let me know if I missed anything or if anything seems like it doesn't belong.

@mdjermanovic you're still planning to work on `eslint-release` to allow concurrent v8.x and v9.x releases?

I'm wondering if we should publish maintenance releases to a different npm tag, like `eslint@maintenance`?

**Comment by mdjermanovic** [comment]
> @mdjermanovic you're still planning to work on `eslint-release` to allow concurrent v8.x and v9.x releases?

Yes. I'll open an issue with a list of tasks.

**Comment by nzakas** [comment]
@joeeames do we want to do an announcement? I'm thinking it would be good to formally announce the v8.x end of life along with the HeroDevs partnership?

**Comment by joeeames** [comment]
@nzakas that sounds like a good idea. What normal channels would your team use for an announcement? what social media/blog do you have?

we do have an entire marketing team that loves to go hog wild about stuff like this, they can ghost write blogs and tweets for you to approve and post. and post some things on our site. Isn't there also something OpenJS has like a blog?

**Comment by nzakas** [comment]
@joeeames we typically announce things on our [blog](https://eslint.org/blog/category/announcements/), [Twitter](https://twitter.com/geteslint), and [Mastodon](https://fosstodon.org/@eslint). 

Once we do that, we get the OpenJS team to retweet and share.

The way I see it, there are three things to cover:

1. The official EOL announcement for v8.x
2. The announcement of the new version support policy
3. The announcement of partnering with HeroDevs

I'm unsure if that should all be in one post or not. Definitely open to suggestions.

**Comment by joeeames** [comment]
let me loop in our marketing people and get their input. they're out for Black Hat, so it'll probably be tomorrow on that.

One thing I wanted to mention from the previous Issue re: the github README. We didn't get that change implemented with info on the README. my screenshot of the proposed change didn't actually show up in the initial post in the issue (I may have forgotten to include it). What are your thoughts on that?  

Here's some proposed content for the readme:
![readme](https://github.com/user-attachments/assets/15643497-bd3f-40f7-9a2d-01963a7e1b30)

**Comment by nzakas** [comment]
I'd suggest more closely matching the text on the version support page, so something like:

> The ESLint team provides ongoing support for the current version and six months of limited support for the previous version. Limited support includes critical bug fixes, security issues, and compatibility issues only.
>
> ESLint offers commercial support for both current and previous versions through our partners, Tidelift and HeroDevs.
>
> See [Version Support](https://eslint.org/version-support) for more details.

In general, I like to keep specific version mentions out of the README because it's easy to forget to update those. :)

**Comment by joeeames** [comment]
PR submitted.

**Comment by nzakas** [comment]
@joeeames just checking back on doing an announcement. Any update on that?

**Comment by joeeames** [comment]
hey @nzakas apologies for the delay. lots of movement on our side on various projects. 

We'd love to help with the announcement. I'll email you to begin coordination.

**Comment by nzakas** [comment]
Everything is complete, so closing.
