### ISSUE TITLE
Roadmap: 2.0.0

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#3561]
This issue is a tracking issue so we can more easily see what we're working towards for ESLint v2.0.0. These tasks won't necessarily wait for 2.0.0, but rather, we will know it's time for 2.0.0 once the non-breaking items in this list are complete. At that point, we can start working on the breaking changes and prepare for 2.0.0. For context on many of these, see #2203.

These are *not* in priority order:

- [x] Autofixing certain errors (lead: @nzakas, #3134)
- [x] Autocreate configuration based on code sample (lead: @ianvs #3567)
- [x] Suffixed `.eslintrc` files (lead: @nzakas, #4045)
- [x] Code path analysis (lead: @mysticatea, #3530)
- [x] **Breaking:** Treat `package.json` like `.eslintrc` (lead: @nzakas, #4451)
- [x] **Breaking:** Update `eslint:recommended` rules list (lead: ?)
- [x] **Breaking:** Create `yield-star-spacing` (lead: ?, #4115)
- [x] **Breaking:** Move ES6 globals from `builtin` to `es6` environment (lead: @nzakas, #4085)
- [x] **Breaking:** Cleaner JSON Schemas for rules (lead: @btmills , #3625)
- [x] **Breaking:** Make `.eslintignore` work exactly like `.gitignore` (lead: @JulianLaval, #2365)
- [x] **Breaking:** Ignore bower_components by default (lead: @JulianLaval, #3550)

This issue will be closed when all of the subissues are complete. We may add more into this list as needed.

**Comment by btmills** [comment]
I can take lead on cleaner schemas for #3625.

**Comment by nzakas** [comment]
Great, updated the description

**Comment by platinumazure** [comment]
What sort of approach should be taken for updating the `eslint:recommended` list?

**Comment by nzakas** [comment]
We just need to see if there are any other rules that should be on by default to avoid possible errors.

**Comment by puzrin** [comment]
I've tried 2.0beta2 on my projects. Everything looks nice except one too restrictive behaviour in `indent` rule #5073. It would be nice if it could be fixed for 2.0 (or, at least, not frozen to 3.0)

**Comment by nzakas** [comment]
Looks like we've cleared the board for 2.0.0, so closing.

**Comment by CrabDude** [comment]
It seems all roads end here for "glob matching" / "config by file extension" / --ext in config.

Where has this (previously on the roadmap) feature gone?* (Solely seeking information)
Are there any (post-2.0.0) open/tracking issues or discussions on glob-matching/file-ext config?

See https://github.com/eslint/eslint/issues/2203#issuecomment-120438720, https://github.com/eslint/eslint/issues/2274#issuecomment-91391976, https://github.com/eslint/eslint/issues/2473#issuecomment-100518963, https://github.com/eslint/eslint/issues/2565#issuecomment-103420825, https://github.com/eslint/eslint/issues/2958#issuecomment-119965282, https://github.com/eslint/eslint/issues/3105#issuecomment-123380033, https://github.com/eslint/eslint/issues/3105#issuecomment-123303083
CC @lo1tuma, @ilyavolodin, @btmills,

**Comment by IanVS** [comment]
@CrabDude the tracking issue is: https://github.com/eslint/eslint/issues/3611
