### ISSUE TITLE
Proposal for 3.0.0

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#6356]
We have a few breaking changes that are getting backed up, and I think it would be nice to publish them and put out 3.0.0. We won't get much in the way of new functionality, but I think it will solve some problems for people. So, I'd like to propose the following for a 3.0.0 release in the next few weeks:

- [x] Drop support for Node.js < 4 (LTS version) (https://github.com/eslint/eslint/issues/4483)
- [x] Update `eslint:recommended` (with whatever is appropriate) (https://github.com/eslint/eslint/issues/6403)
- [x] Set a default value for `complexity` (https://github.com/eslint/eslint/issues/6021)
- [x] Output error if no config file is found (https://github.com/eslint/eslint/issues/5987)
- [x] ~~Use XDG basedirs for personal config file (https://github.com/eslint/eslint/issues/6008)~~
- [x] Suppress ignored file warnings in `executeOnText()` (https://github.com/eslint/eslint/issues/6302)
- [x] Simplify eslint process exit code (https://github.com/eslint/eslint/issues/6368)

A lot of these are fairly simple changes that could have positive impacts on end users, so maybe we can swarm and get these done?

Thoughts?

**Comment by alberto** [comment]
@nzakas #6008 isn't accepted

**Comment by nzakas** [comment]
@alberto I know, I'm proposing that we accept it.

**Comment by nzakas** [comment]
Oops, I thought it was closer than it is. Looks like there are still open questions on #6008, so removing from this proposal.

**Comment by nzakas** [comment]
@eslint/eslint-team please let me know what you think.

**Comment by ilyavolodin** [comment]
LGTM. It's a pretty small release, but I think that's fine. For dropping Node < 4, should we also convert the code to use some of the ES6 features at the same time, as well as modify our .eslintrc file for this repository? Or should we leave it as is and change it as we go?

**Comment by platinumazure** [comment]
My vote is change as we go, since those are chores that could be done anytime.

**Comment by vitorbal** [comment]
I also think change as we go is fine. Do we already know which es6 rules we
would like to turn on?

**Comment by alberto** [comment]
Added #6368 to the list.

**Comment by alberto** [comment]
LGTM.

Also :+1 to convert as we go

**Comment by mikesherov** [comment]
If we're going to start using es6, we should consider using https://github.com/mohebifar/lebab if we're going to upconvert. 

Mike Sherov

**Comment by mysticatea** [comment]
I also give :+1: to convert the code to use some of the ES6 features, and I'd like to use `eslint-plugin-node` :innocent:

- [node/no-deprecated-api](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-deprecated-api.md) - Disallow deprecated API.
- [node/no-missing-require](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-missing-require.md) - Disallow `require()`s for files that don't exist.
- [node/no-unpublished-require](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unpublished-require.md) - Disallow `require()`s for files that are not published.
- [node/no-unsupported-features](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unsupported-features.md) - Disallow unsupported ECMAScript features on the specified version.

Also, I have some concerns about plugins loading.

- https://github.com/eslint/eslint/issues/5160#issuecomment-181222353
- #6362

If we solve those, it may be with some breaking changes.

**Comment by michaelficarra** [comment]
#6298 is a breaking change that hasn't reached consensus yet, but which I would like to be considered. The problem, though, is that it may take a decent amount of work, and may not be ready in the next few weeks.

**Comment by platinumazure** [comment]
@michaelficarra I greatly appreciate you offering my proposal, but I don't see it making 3.x and I'm okay with that. Also, I don't think it has to be a breaking change: rules which could use repository settings could continue to allow rule-level config as a backward compatibility layer. Thus I see no reason to add the proposal to 3.x.

**Comment by michaelficarra** [comment]
@platinumazure That's right, though I was hoping we could deprecate the old configuration in a major release.

**Comment by mysticatea** [comment]
If we deprecate old configurations, I'd like to get glob-based configuration :smiley:

**Comment by ilyavolodin** [comment]
@michaelficarra If you support repository based configuration, could you post your thoughts on it in #6298 right now, I'm not sure I understand what problem we are trying to solve with it.

**Comment by michaelficarra** [comment]
@ilyavolodin I will post there soon. I just haven't had the time to write up a convincing argument recently.

**Comment by nzakas** [comment]
Let's table the converting to ES6 discussion for now (if someone wants to open up a separate issue to discuss, please do, but that will come after 3.0.0 and so isn't relevant to planning).

And please, let's not add any more issues to my original description unless we all agree first. Otherwise, the reactions on that description and the comments are a bit misleading.

Part of the rationale for doing 3.0.0 in this lightweight way is to avoid the breaking feature explosion we've tended to have with previous major release (where everyone wants to get in "just one more" breaking change). That's also meant the nightmare of doing alpha and beta releases, which I definitely would like to avoid going forward.

I'd say at this point the only thing we should do is remove issues from the list and not add them. With what we have, I think we can shoot for 3.0.0 next Friday. Sound reasonable?

**Comment by alberto** [comment]
Sorry. I took the liberty to include that issue since it would become dead code as part of the node support update (you could consider it part of that), but I get your point. ❤️

**Comment by mysticatea** [comment]
I'm sorry. Sounds good to me.

**Comment by vitorbal** [comment]
I opened a separate issue to continue the converting to ES6 discussion: #6407

**Comment by nathanhammond** [comment]
@nzakas et al.: Ember and Ember CLI have committed to supporting the Node LTS lifetimes for the HEAD of our master branch(es). This means that we will will drop support for 0.10 on 2016-10-01 and 0.12 on 2016-12-31 per the [Node.js Long-term Support Working Group's schedule](https://github.com/nodejs/LTS#lts-schedule).

We recognize that we don't have the privilege of setting that default for the entire Node ecosystem and have reserved the option to change that in the future if we find ourselves maintaining our own forks or legacy versions of the entire world.

_This comment should be considered informational._ 😄 The only consequence is that we won't move the Ember ecosystem to 3.X until January of next year.

/cc @stefanpenner @Turbo87 @rwjblue

**Comment by alberto** [comment]
Closing, since this is already done.

@nathanhammond you can use eslint@3 to lint your codebase using node>=4 even if you still support older node versions yourself.

**Comment by nathanhammond** [comment]
Hey @alberto, I appreciate the quick note.

There is a minor distinction that has to be made which makes all the difference: we're not aiming to lint _our_ code (Ember CLI), we're aiming to lint the code of people who build applications using Ember CLI.

As we're delivering a bundled development tool we need to make sure that our upstreams (ESLint) support our target versions. Our support promise at current is such that you can build on top of our tooling and use any of the presently-supported versions of Node.

This means that we will continue to use ESLint@2 until the end of the year inside of the Ember community. This isn't a complaint, it should be considered informational (especially since the lag time here is limited), but do keep this in mind for when you elect to drop 4.X support at some point in the future.

/cc @erisds

**Comment by alberto** [comment]
Ah, gotcha. Thanks for your feedback, we'll take that into account.

**Comment by ErisDS** [comment]
Ghost has also committed to following the Node.js LTS roadmap. We have official support for LTS versions only, and drop support for old versions on the dates laid out in that plan. 

We'd like to encourage as much of the Node.js ecosystem as possible to commit to following this plan, dropping support for older Node.js versions on the dates laid out. If we all drop support on the same day, this sends a clear message to the wider community that LTS means what it says 😉 . By validating & throwing weight behind Node.js LTS, we can help to position Node.js a reliable, dependable tool for SMBs & enterprise alike, and contribute to improving the reputation of the ecosystem.

This is just my 2c though 😁
