### ISSUE TITLE
Refactor how .eslintignore works

### ISSUE THREAD

**Issue by nzakas** [eslint/eslint#928]
There are a number of issues already open around how ignored files work (or don't work). They are:
- [x] Performance problems (#901 and #814)
- [x] Files in ignored directories still linted when specified on command line (#837)
- [x] ESLint can't pass files and directories at the same time (#853)

We've also patched ignored files a bunch in the last release.

It's become clear to me that there's a problem with the way the ignored file functionality is implemented at a fundamental level. It's time to refactor and clean this mess up.
